# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TufClientCli < Formula
  desc "TUF client CLI written in Go based on the rdimitrov/go-tuf-metadata library."
  homepage "https://github.com/rdimitrov/tuf-client-cli"
  version "0.0.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rdimitrov/tuf-client-cli/releases/download/v0.0.12/tuf-client-cli-darwin-amd64"
      sha256 "3f03f17bc3f758d910d0265d1bdc4d11a071fd01a25ada527a4ef753445e45fc"

      def install
        bin.install "tuf-client-cli-darwin-amd64" => "tuf-client-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rdimitrov/tuf-client-cli/releases/download/v0.0.12/tuf-client-cli-darwin-arm64"
      sha256 "d2afdeb7568f017cf56f7768432cd5d9bde3f6fca69838b575850d781ff5eb43"

      def install
        bin.install "tuf-client-cli-darwin-arm64" => "tuf-client-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/rdimitrov/tuf-client-cli/releases/download/v0.0.12/tuf-client-cli-linux-amd64"
      sha256 "1dcfa44010434a141b1768caa0e8eb3de3b4421d564a7eca69da812f3d269893"

      def install
        bin.install "tuf-client-cli-linux-amd64" => "tuf-client-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rdimitrov/tuf-client-cli/releases/download/v0.0.12/tuf-client-cli-linux-arm64"
      sha256 "a4eb03cfe14879e09372377218b09b653e7b36790723e207924ece270b50f937"

      def install
        bin.install "tuf-client-cli-linux-arm64" => "tuf-client-cli"
      end
    end
  end
end
