# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TufClient < Formula
  desc "TUF client CLI written in Go based on the rdimitrov/go-tuf-metadata library."
  homepage "https://github.com/rdimitrov/tuf-client-cli"
  version "0.0.7"

  on_macos do
    on_intel do
      url "https://github.com/rdimitrov/tuf-client-cli/releases/download/v0.0.7/tuf-client_0.0.7_darwin_amd64.tar.gz"
      sha256 "de481673cfec934e85678cc4e6b85523e577d98a3e6603501e322567f4a603dc"

      def install
        bin.install "tuf-client"
      end
    end
    on_arm do
      url "https://github.com/rdimitrov/tuf-client-cli/releases/download/v0.0.7/tuf-client_0.0.7_darwin_arm64.tar.gz"
      sha256 "687872189615fc7a1d7d267b9b5a1238b3568cc7695c90032f51376a2a00c694"

      def install
        bin.install "tuf-client"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rdimitrov/tuf-client-cli/releases/download/v0.0.7/tuf-client_0.0.7_linux_amd64.tar.gz"
        sha256 "c257727853664b31b8c6f905aead0aa7f69ea44b704be61f52462f8b45d1a424"

        def install
          bin.install "tuf-client"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rdimitrov/tuf-client-cli/releases/download/v0.0.7/tuf-client_0.0.7_linux_arm64.tar.gz"
        sha256 "5e5298a62de73bcf11368690056078f5f749c55d53e24f70cfd7bc4bbeff89a1"

        def install
          bin.install "tuf-client"
        end
      end
    end
  end

  test do
    system "#{bin}/tuf-client --help"
  end
end
