# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TufClient < Formula
  desc "TUF client CLI written in Go based on the rdimitrov/go-tuf-metadata library."
  homepage "https://github.com/rdimitrov/tuf-client-cli"
  version "0.0.7"

  on_macos do
    on_intel do
      url "https://github.com/rdimitrov/tuf-client-cli/releases/download/v0.0.7/tuf-client_0.0.7_darwin_amd64.tar.gz"
      sha256 "bd392700099d9ff695451cce2446935c4879112dbd75721393a144fb3813d469"

      def install
        bin.install "tuf-client"
      end
    end
    on_arm do
      url "https://github.com/rdimitrov/tuf-client-cli/releases/download/v0.0.7/tuf-client_0.0.7_darwin_arm64.tar.gz"
      sha256 "eb20208901fa6bd7f36bba43c62bd30075af882d4bfbabacf113ae14e2d1cf86"

      def install
        bin.install "tuf-client"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rdimitrov/tuf-client-cli/releases/download/v0.0.7/tuf-client_0.0.7_linux_amd64.tar.gz"
        sha256 "4219e19b2753f55a9ad709f86c3d49edf47b30f2d9addb6f71453df58f49245e"

        def install
          bin.install "tuf-client"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/rdimitrov/tuf-client-cli/releases/download/v0.0.7/tuf-client_0.0.7_linux_arm64.tar.gz"
        sha256 "d024cb8bc79ebf6bb7cfaf4274736d389b91474c8868fb78af31dac76e8b7c39"

        def install
          bin.install "tuf-client"
        end
      end
    end
  end

  test do
    system "#{bin}/tuf-client --help"
  end
end
